[package]
name = "example-barebone"
version = "0.1.0"
edition = "2021"

[dependencies]
# FIXME: Remove unnessary features
rustpython-vm = { path = "../../vm", default-features = false, features = ["compiler", "ast"] }

[workspace]
