[package]
name = "example-barebone"
version = "0.1.0"
edition = "2021"

[dependencies]
rustpython-vm = { path = "../../vm", default-features = false }
rustpython = { path = "../.." }
env_logger = "0.11.6"

[workspace]
