include = [
    "examples/**/*.py",
    "extra_tests/**/*.py",
    "wasm/**/*.py",
]

exclude = [
    ".*",
    "Lib",
    "vm/Lib",
    "benches",
    "syntax_*.py", # Do not format files that are specifically testing for syntax
    "badsyntax_*.py",
]

[lint]
select = [
    "E9", # pycodestyle (error)
    "F63", # pyflakes
    "F7",
    "F82",
]
