use sre_engine::engine;

struct Pattern {
    code: &'static [u32],
}

impl Pattern {
    fn state<'a, S: engine::StrDrive>(
        &self,
        string: S,
    ) -> (engine::Request<'a, S>, engine::State) {
        let req = engine::Request::new(string, 0, usize::MAX, self.code, false);
        let state = engine::State::default();
        (req, state)
    }
}

#[test]
fn test_2427() {
    // pattern lookbehind = re.compile(r'(?<!\.)x\b')
    // START GENERATED by generate_tests.py
    #[rustfmt::skip] let lookbehind = Pattern { code: &[14, 4, 0, 1, 1, 5, 5, 1, 16, 46, 1, 16, 120, 6, 10, 1] };
    // END GENERATED
    let (req, mut state) = lookbehind.state("x");
    assert!(state.pymatch(&req));
}

#[test]
fn test_assert() {
    // pattern positive_lookbehind = re.compile(r'(?<=abc)def')
    // START GENERATED by generate_tests.py
    #[rustfmt::skip] let positive_lookbehind = Pattern { code: &[14, 4, 0, 3, 3, 4, 9, 3, 16, 97, 16, 98, 16, 99, 1, 16, 100, 16, 101, 16, 102, 1] };
    // END GENERATED
    let (req, mut state) = positive_lookbehind.state("abcdef");
    assert!(state.search(req));
}

#[test]
fn test_string_boundaries() {
    // pattern big_b = re.compile(r'\B')
    // START GENERATED by generate_tests.py
    #[rustfmt::skip] let big_b = Pattern { code: &[14, 4, 0, 0, 0, 6, 11, 1] };
    // END GENERATED
    let (req, mut state) = big_b.state("");
    assert!(!state.search(req));
}

#[test]
fn test_zerowidth() {
    // pattern p = re.compile(r'\b|:+')
    // START GENERATED by generate_tests.py
    #[rustfmt::skip] let p = Pattern { code: &[14, 4, 0, 0, 4294967295, 7, 5, 6, 10, 15, 12, 10, 24, 6, 1, 4294967295, 16, 58, 1, 15, 2, 0, 1] };
    // END GENERATED
    let (mut req, mut state) = p.state("a:");
    req.must_advance = true;
    assert!(state.search(req));
    assert_eq!(state.string_position, 1);
}

#[test]
fn test_repeat_context_panic() {
    use optional::Optioned;
    // pattern p = re.compile(r'(?:a*?(xx)??z)*')
    // START GENERATED by generate_tests.py
    #[rustfmt::skip] let p = Pattern { code: &[14, 4, 0, 0, 4294967295, 23, 25, 0, 4294967295, 26, 6, 0, 4294967295, 16, 97, 1, 23, 11, 0, 1, 17, 0, 16, 120, 16, 120, 17, 1, 19, 16, 122, 18, 1] };
    // END GENERATED
    let (req, mut state) = p.state("axxzaz");
    assert!(state.pymatch(&req));
    assert_eq!(*state.marks.raw(), vec![Optioned::some(1), Optioned::some(3)]);
}

#[test]
fn test_double_max_until() {
    // pattern p = re.compile(r'((1)?)*')
    // START GENERATED by generate_tests.py
    #[rustfmt::skip] let p = Pattern { code: &[14, 4, 0, 0, 4294967295, 23, 18, 0, 4294967295, 17, 0, 23, 9, 0, 1, 17, 2, 16, 49, 17, 3, 18, 17, 1, 18, 1] };
    // END GENERATED
    let (req, mut state) = p.state("1111");
    assert!(state.pymatch(&req));
    assert_eq!(state.string_position, 4);
}

#[test]
fn test_info_single() {
    // pattern p = re.compile(r'aa*')
    // START GENERATED by generate_tests.py
    #[rustfmt::skip] let p = Pattern { code: &[14, 8, 1, 1, 4294967295, 1, 1, 97, 0, 16, 97, 24, 6, 0, 4294967295, 16, 97, 1, 1] };
    // END GENERATED
    let (req, mut state) = p.state("baaaa");
    assert!(state.search(req));
    assert_eq!(state.start, 1);
    assert_eq!(state.string_position, 5);
}

#[test]
fn test_info_single2() {
    // pattern p = re.compile(r'Python|Perl')
    // START GENERATED by generate_tests.py
    #[rustfmt::skip] let p = Pattern { code: &[14, 8, 1, 4, 6, 1, 1, 80, 0, 16, 80, 7, 13, 16, 121, 16, 116, 16, 104, 16, 111, 16, 110, 15, 11, 9, 16, 101, 16, 114, 16, 108, 15, 2, 0, 1] };
    // END GENERATED
    let (req, mut state) = p.state("Perl");
    assert!(state.search(req));
}

#[test]
fn test_info_literal() {
    // pattern p = re.compile(r'ababc+')
    // START GENERATED by generate_tests.py
    #[rustfmt::skip] let p = Pattern { code: &[14, 14, 1, 5, 4294967295, 4, 4, 97, 98, 97, 98, 0, 0, 1, 2, 16, 97, 16, 98, 16, 97, 16, 98, 24, 6, 1, 4294967295, 16, 99, 1, 1] };
    // END GENERATED
    let (req, mut state) = p.state("!ababc");
    assert!(state.search(req));
}

#[test]
fn test_info_literal2() {
    // pattern p = re.compile(r'(python)\1')
    // START GENERATED by generate_tests.py
    #[rustfmt::skip] let p = Pattern { code: &[14, 18, 1, 12, 12, 6, 0, 112, 121, 116, 104, 111, 110, 0, 0, 0, 0, 0, 0, 17, 0, 16, 112, 16, 121, 16, 116, 16, 104, 16, 111, 16, 110, 17, 1, 11, 0, 1] };
    // END GENERATED
    let (req, mut state) = p.state("pythonpython");
    assert!(state.search(req));
}

#[test]
fn test_repeat_in_assertions() {
    // pattern p = re.compile('^([ab]*?)(?=(b)?)c', re.IGNORECASE)
    // START GENERATED by generate_tests.py
    #[rustfmt::skip] let p = Pattern { code: &[14, 4, 0, 1, 4294967295, 6, 0, 17, 0, 26, 10, 0, 4294967295, 39, 5, 22, 97, 98, 0, 1, 17, 1, 4, 14, 0, 23, 9, 0, 1, 17, 2, 40, 98, 17, 3, 18, 1, 40, 99, 1] };
    // END GENERATED
    let (req, mut state) = p.state("abc");
    assert!(state.search(req));
}