//! Python opcode implementation. Currently aligned with cpython 3.13.7

// This file is generated by scripts/gen_opcodes.py
// Do not edit!

/// Python opcode
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum Opcode {
    BeforeAsyncWith = 1,
    BeforeWith = 2,
    BinaryOp = 45,
    BinaryOpAddFloat = 150,
    BinaryOpAddInt = 151,
    BinaryOpAddUnicode = 152,
    BinaryOpInplaceAddUnicode = 3,
    BinaryOpMultiplyFloat = 153,
    BinaryOpMultiplyInt = 154,
    BinaryOpSubtractFloat = 155,
    BinaryOpSubtractInt = 156,
    BinarySlice = 4,
    BinarySubscr = 5,
    BinarySubscrDict = 157,
    BinarySubscrGetitem = 158,
    BinarySubscrListInt = 159,
    BinarySubscrStrInt = 160,
    BinarySubscrTupleInt = 161,
    BuildConstKeyMap = 46,
    BuildList = 47,
    BuildMap = 48,
    BuildSet = 49,
    BuildSlice = 50,
    BuildString = 51,
    BuildTuple = 52,
    Cache = 0,
    Call = 53,
    CallAllocAndEnterInit = 162,
    CallBoundMethodExactArgs = 163,
    CallBoundMethodGeneral = 164,
    CallBuiltinClass = 165,
    CallBuiltinFast = 166,
    CallBuiltinFastWithKeywords = 167,
    CallBuiltinO = 168,
    CallFunctionEx = 54,
    CallIntrinsic1 = 55,
    CallIntrinsic2 = 56,
    CallIsinstance = 169,
    CallKw = 57,
    CallLen = 170,
    CallListAppend = 171,
    CallMethodDescriptorFast = 172,
    CallMethodDescriptorFastWithKeywords = 173,
    CallMethodDescriptorNoargs = 174,
    CallMethodDescriptorO = 175,
    CallNonPyGeneral = 176,
    CallPyExactArgs = 177,
    CallPyGeneral = 178,
    CallStr1 = 179,
    CallTuple1 = 180,
    CallType1 = 181,
    CheckEgMatch = 6,
    CheckExcMatch = 7,
    CleanupThrow = 8,
    CompareOp = 58,
    CompareOpFloat = 182,
    CompareOpInt = 183,
    CompareOpStr = 184,
    ContainsOp = 59,
    ContainsOpDict = 185,
    ContainsOpSet = 186,
    ConvertValue = 60,
    Copy = 61,
    CopyFreeVars = 62,
    DeleteAttr = 63,
    DeleteDeref = 64,
    DeleteFast = 65,
    DeleteGlobal = 66,
    DeleteName = 67,
    DeleteSubscr = 9,
    DictMerge = 68,
    DictUpdate = 69,
    EndAsyncFor = 10,
    EndFor = 11,
    EndSend = 12,
    EnterExecutor = 70,
    ExitInitCheck = 13,
    ExtendedArg = 71,
    FormatSimple = 14,
    FormatWithSpec = 15,
    ForIter = 72,
    ForIterGen = 187,
    ForIterList = 188,
    ForIterRange = 189,
    ForIterTuple = 190,
    GetAiter = 16,
    GetAnext = 18,
    GetAwaitable = 73,
    GetIter = 19,
    GetLen = 20,
    GetYieldFromIter = 21,
    ImportFrom = 74,
    ImportName = 75,
    InstrumentedCall = 244,
    InstrumentedCallFunctionEx = 246,
    InstrumentedCallKw = 245,
    InstrumentedEndFor = 237,
    InstrumentedEndSend = 238,
    InstrumentedForIter = 243,
    InstrumentedInstruction = 247,
    InstrumentedJumpBackward = 249,
    InstrumentedJumpForward = 248,
    InstrumentedLoadSuperAttr = 242,
    InstrumentedPopJumpIfFalse = 251,
    InstrumentedPopJumpIfNone = 252,
    InstrumentedPopJumpIfNotNone = 253,
    InstrumentedPopJumpIfTrue = 250,
    InstrumentedResume = 236,
    InstrumentedReturnConst = 240,
    InstrumentedReturnValue = 239,
    InstrumentedYieldValue = 241,
    InterpreterExit = 22,
    IsOp = 76,
    JumpBackward = 77,
    JumpBackwardNoInterrupt = 78,
    JumpForward = 79,
    ListAppend = 80,
    ListExtend = 81,
    LoadAssertionError = 23,
    LoadAttr = 82,
    LoadAttrClass = 191,
    LoadAttrGetattributeOverridden = 192,
    LoadAttrInstanceValue = 193,
    LoadAttrMethodLazyDict = 194,
    LoadAttrMethodNoDict = 195,
    LoadAttrMethodWithValues = 196,
    LoadAttrModule = 197,
    LoadAttrNondescriptorNoDict = 198,
    LoadAttrNondescriptorWithValues = 199,
    LoadAttrProperty = 200,
    LoadAttrSlot = 201,
    LoadAttrWithHint = 202,
    LoadBuildClass = 24,
    LoadConst = 83,
    LoadDeref = 84,
    LoadFast = 85,
    LoadFastAndClear = 86,
    LoadFastCheck = 87,
    LoadFastLoadFast = 88,
    LoadFromDictOrDeref = 89,
    LoadFromDictOrGlobals = 90,
    LoadGlobal = 91,
    LoadGlobalBuiltin = 203,
    LoadGlobalModule = 204,
    LoadLocals = 25,
    LoadName = 92,
    LoadSuperAttr = 93,
    LoadSuperAttrAttr = 205,
    LoadSuperAttrMethod = 206,
    MakeCell = 94,
    MakeFunction = 26,
    MapAdd = 95,
    MatchClass = 96,
    MatchKeys = 27,
    MatchMapping = 28,
    MatchSequence = 29,
    Nop = 30,
    PopExcept = 31,
    PopJumpIfFalse = 97,
    PopJumpIfNone = 98,
    PopJumpIfNotNone = 99,
    PopJumpIfTrue = 100,
    PopTop = 32,
    PushExcInfo = 33,
    PushNull = 34,
    RaiseVarargs = 101,
    Reraise = 102,
    Reserved = 17,
    Resume = 149,
    ResumeCheck = 207,
    ReturnConst = 103,
    ReturnGenerator = 35,
    ReturnValue = 36,
    Send = 104,
    SendGen = 208,
    SetupAnnotations = 37,
    SetAdd = 105,
    SetFunctionAttribute = 106,
    SetUpdate = 107,
    StoreAttr = 108,
    StoreAttrInstanceValue = 209,
    StoreAttrSlot = 210,
    StoreAttrWithHint = 211,
    StoreDeref = 109,
    StoreFast = 110,
    StoreFastLoadFast = 111,
    StoreFastStoreFast = 112,
    StoreGlobal = 113,
    StoreName = 114,
    StoreSlice = 38,
    StoreSubscr = 39,
    StoreSubscrDict = 212,
    StoreSubscrListInt = 213,
    Swap = 115,
    ToBool = 40,
    ToBoolAlwaysTrue = 214,
    ToBoolBool = 215,
    ToBoolInt = 216,
    ToBoolList = 217,
    ToBoolNone = 218,
    ToBoolStr = 219,
    UnaryInvert = 41,
    UnaryNegative = 42,
    UnaryNot = 43,
    UnpackEx = 116,
    UnpackSequence = 117,
    UnpackSequenceList = 220,
    UnpackSequenceTuple = 221,
    UnpackSequenceTwoTuple = 222,
    WithExceptStart = 44,
    YieldValue = 118,
    Jump = 256,
    JumpNoInterrupt = 257,
    LoadClosure = 258,
    LoadMethod = 259,
    LoadSuperMethod = 260,
    LoadZeroSuperAttr = 261,
    LoadZeroSuperMethod = 262,
    PopBlock = 263,
    SetupCleanup = 264,
    SetupFinally = 265,
    SetupWith = 266,
    StoreFastMaybeNull = 267,
}

impl Opcode {
    /// Whether the given ID matches one of the opcode IDs.
    #[must_use]
    pub const fn is_valid(id: u16) -> bool {
        matches!(id, 0..=118 | 149..=222 | 236..=253 | 256..=267)
    }

    /// Whether opcode ID is pseudo.
    #[must_use]
    pub const fn is_pseudo(&self) -> bool {
        matches!(
            *self,
            Self::Jump
                | Self::JumpNoInterrupt
                | Self::LoadClosure
                | Self::LoadMethod
                | Self::LoadSuperMethod
                | Self::LoadZeroSuperAttr
                | Self::LoadZeroSuperMethod
                | Self::PopBlock
                | Self::SetupCleanup
                | Self::SetupFinally
                | Self::SetupWith
                | Self::StoreFastMaybeNull
        )
    }

    /// Whether opcode ID have 'HAS_ARG_FLAG' set.
    #[must_use]
    pub const fn has_arg(&self) -> bool {
        matches!(
            *self,
            Self::BinaryOp
                | Self::BuildConstKeyMap
                | Self::BuildList
                | Self::BuildMap
                | Self::BuildSet
                | Self::BuildSlice
                | Self::BuildString
                | Self::BuildTuple
                | Self::Call
                | Self::CallAllocAndEnterInit
                | Self::CallBoundMethodExactArgs
                | Self::CallBoundMethodGeneral
                | Self::CallBuiltinClass
                | Self::CallBuiltinFast
                | Self::CallBuiltinFastWithKeywords
                | Self::CallBuiltinO
                | Self::CallFunctionEx
                | Self::CallIntrinsic1
                | Self::CallIntrinsic2
                | Self::CallIsinstance
                | Self::CallKw
                | Self::CallLen
                | Self::CallListAppend
                | Self::CallMethodDescriptorFast
                | Self::CallMethodDescriptorFastWithKeywords
                | Self::CallMethodDescriptorNoargs
                | Self::CallMethodDescriptorO
                | Self::CallNonPyGeneral
                | Self::CallPyExactArgs
                | Self::CallPyGeneral
                | Self::CallStr1
                | Self::CallTuple1
                | Self::CallType1
                | Self::CompareOp
                | Self::CompareOpFloat
                | Self::CompareOpInt
                | Self::CompareOpStr
                | Self::ContainsOp
                | Self::ContainsOpDict
                | Self::ContainsOpSet
                | Self::ConvertValue
                | Self::Copy
                | Self::CopyFreeVars
                | Self::DeleteAttr
                | Self::DeleteDeref
                | Self::DeleteFast
                | Self::DeleteGlobal
                | Self::DeleteName
                | Self::DictMerge
                | Self::DictUpdate
                | Self::EnterExecutor
                | Self::ExtendedArg
                | Self::ForIter
                | Self::ForIterGen
                | Self::ForIterList
                | Self::ForIterRange
                | Self::ForIterTuple
                | Self::GetAwaitable
                | Self::ImportFrom
                | Self::ImportName
                | Self::InstrumentedCall
                | Self::InstrumentedCallKw
                | Self::InstrumentedForIter
                | Self::InstrumentedJumpBackward
                | Self::InstrumentedJumpForward
                | Self::InstrumentedLoadSuperAttr
                | Self::InstrumentedPopJumpIfFalse
                | Self::InstrumentedPopJumpIfNone
                | Self::InstrumentedPopJumpIfNotNone
                | Self::InstrumentedPopJumpIfTrue
                | Self::InstrumentedResume
                | Self::InstrumentedReturnConst
                | Self::InstrumentedYieldValue
                | Self::IsOp
                | Self::JumpBackward
                | Self::JumpBackwardNoInterrupt
                | Self::JumpForward
                | Self::ListAppend
                | Self::ListExtend
                | Self::LoadAttr
                | Self::LoadAttrClass
                | Self::LoadAttrGetattributeOverridden
                | Self::LoadAttrInstanceValue
                | Self::LoadAttrMethodLazyDict
                | Self::LoadAttrMethodNoDict
                | Self::LoadAttrMethodWithValues
                | Self::LoadAttrModule
                | Self::LoadAttrNondescriptorNoDict
                | Self::LoadAttrNondescriptorWithValues
                | Self::LoadAttrProperty
                | Self::LoadAttrSlot
                | Self::LoadAttrWithHint
                | Self::LoadConst
                | Self::LoadDeref
                | Self::LoadFast
                | Self::LoadFastAndClear
                | Self::LoadFastCheck
                | Self::LoadFastLoadFast
                | Self::LoadFromDictOrDeref
                | Self::LoadFromDictOrGlobals
                | Self::LoadGlobal
                | Self::LoadGlobalBuiltin
                | Self::LoadGlobalModule
                | Self::LoadName
                | Self::LoadSuperAttr
                | Self::LoadSuperAttrAttr
                | Self::LoadSuperAttrMethod
                | Self::MakeCell
                | Self::MapAdd
                | Self::MatchClass
                | Self::PopJumpIfFalse
                | Self::PopJumpIfNone
                | Self::PopJumpIfNotNone
                | Self::PopJumpIfTrue
                | Self::RaiseVarargs
                | Self::Reraise
                | Self::Resume
                | Self::ReturnConst
                | Self::Send
                | Self::SendGen
                | Self::SetAdd
                | Self::SetFunctionAttribute
                | Self::SetUpdate
                | Self::StoreAttr
                | Self::StoreAttrWithHint
                | Self::StoreDeref
                | Self::StoreFast
                | Self::StoreFastLoadFast
                | Self::StoreFastStoreFast
                | Self::StoreGlobal
                | Self::StoreName
                | Self::Swap
                | Self::UnpackEx
                | Self::UnpackSequence
                | Self::UnpackSequenceList
                | Self::UnpackSequenceTuple
                | Self::UnpackSequenceTwoTuple
                | Self::YieldValue
                | Self::Jump
                | Self::JumpNoInterrupt
                | Self::LoadClosure
                | Self::LoadMethod
                | Self::LoadSuperMethod
                | Self::LoadZeroSuperAttr
                | Self::LoadZeroSuperMethod
                | Self::SetupCleanup
                | Self::SetupFinally
                | Self::SetupWith
                | Self::StoreFastMaybeNull
        )
    }

    /// Whether opcode ID have 'HAS_CONST_FLAG' set.
    #[must_use]
    pub const fn has_const(&self) -> bool {
        matches!(
            *self,
            Self::InstrumentedReturnConst | Self::LoadConst | Self::ReturnConst
        )
    }

    /// Whether opcode ID have 'HAS_NAME_FLAG' set.
    #[must_use]
    pub const fn has_name(&self) -> bool {
        matches!(
            *self,
            Self::DeleteAttr
                | Self::DeleteGlobal
                | Self::DeleteName
                | Self::ImportFrom
                | Self::ImportName
                | Self::LoadAttr
                | Self::LoadAttrGetattributeOverridden
                | Self::LoadAttrWithHint
                | Self::LoadFromDictOrGlobals
                | Self::LoadGlobal
                | Self::LoadName
                | Self::LoadSuperAttr
                | Self::LoadSuperAttrAttr
                | Self::LoadSuperAttrMethod
                | Self::StoreAttr
                | Self::StoreAttrWithHint
                | Self::StoreGlobal
                | Self::StoreName
                | Self::LoadMethod
                | Self::LoadSuperMethod
                | Self::LoadZeroSuperAttr
                | Self::LoadZeroSuperMethod
        )
    }

    /// Whether opcode ID have 'HAS_JUMP_FLAG' set.
    #[must_use]
    pub const fn has_jump(&self) -> bool {
        matches!(
            *self,
            Self::ForIter
                | Self::ForIterList
                | Self::ForIterRange
                | Self::ForIterTuple
                | Self::JumpBackward
                | Self::JumpBackwardNoInterrupt
                | Self::JumpForward
                | Self::PopJumpIfFalse
                | Self::PopJumpIfNone
                | Self::PopJumpIfNotNone
                | Self::PopJumpIfTrue
                | Self::Send
                | Self::Jump
                | Self::JumpNoInterrupt
        )
    }

    /// Whether opcode ID have 'HAS_FREE_FLAG' set.
    #[must_use]
    pub const fn has_free(&self) -> bool {
        matches!(
            *self,
            Self::DeleteDeref
                | Self::LoadDeref
                | Self::LoadFromDictOrDeref
                | Self::MakeCell
                | Self::StoreDeref
        )
    }

    /// Whether opcode ID have 'HAS_LOCAL_FLAG' set.
    #[must_use]
    pub const fn has_local(&self) -> bool {
        matches!(
            *self,
            Self::BinaryOpInplaceAddUnicode
                | Self::DeleteFast
                | Self::LoadFast
                | Self::LoadFastAndClear
                | Self::LoadFastCheck
                | Self::LoadFastLoadFast
                | Self::StoreFast
                | Self::StoreFastLoadFast
                | Self::StoreFastStoreFast
                | Self::LoadClosure
                | Self::StoreFastMaybeNull
        )
    }

    /// Whether opcode ID have 'HAS_PURE_FLAG' set.
    #[must_use]
    pub const fn has_exc(&self) -> bool {
        matches!(
            *self,
            Self::Copy
                | Self::EndFor
                | Self::EndSend
                | Self::LoadConst
                | Self::LoadFast
                | Self::Nop
                | Self::PopTop
                | Self::PushNull
                | Self::Swap
                | Self::UnaryNot
                | Self::LoadClosure
                | Self::PopBlock
                | Self::SetupCleanup
                | Self::SetupFinally
                | Self::SetupWith
        )
    }

    /// How many items should be popped from the stack.
    pub const fn num_popped(&self, oparg: u32) -> u32 {
        match &self {
            Self::BeforeAsyncWith => 1,
            Self::BeforeWith => 1,
            Self::BinaryOp => 2,
            Self::BinaryOpAddFloat => 2,
            Self::BinaryOpAddInt => 2,
            Self::BinaryOpAddUnicode => 2,
            Self::BinaryOpInplaceAddUnicode => 2,
            Self::BinaryOpMultiplyFloat => 2,
            Self::BinaryOpMultiplyInt => 2,
            Self::BinaryOpSubtractFloat => 2,
            Self::BinaryOpSubtractInt => 2,
            Self::BinarySlice => 3,
            Self::BinarySubscr => 2,
            Self::BinarySubscrDict => 2,
            Self::BinarySubscrGetitem => 2,
            Self::BinarySubscrListInt => 2,
            Self::BinarySubscrStrInt => 2,
            Self::BinarySubscrTupleInt => 2,
            Self::BuildConstKeyMap => 1 + oparg,
            Self::BuildList => oparg,
            Self::BuildMap => oparg * 2,
            Self::BuildSet => oparg,
            Self::BuildSlice => 2 + (if oparg == 3 { 1 } else { 0 }),
            Self::BuildString => oparg,
            Self::BuildTuple => oparg,
            Self::Cache => 0,
            Self::Call => 2 + oparg,
            Self::CallAllocAndEnterInit => 2 + oparg,
            Self::CallBoundMethodExactArgs => 2 + oparg,
            Self::CallBoundMethodGeneral => 2 + oparg,
            Self::CallBuiltinClass => 2 + oparg,
            Self::CallBuiltinFast => 2 + oparg,
            Self::CallBuiltinFastWithKeywords => 2 + oparg,
            Self::CallBuiltinO => 2 + oparg,
            Self::CallFunctionEx => 3 + (oparg & 1),
            Self::CallIntrinsic1 => 1,
            Self::CallIntrinsic2 => 2,
            Self::CallIsinstance => 2 + oparg,
            Self::CallKw => 3 + oparg,
            Self::CallLen => 2 + oparg,
            Self::CallListAppend => 3,
            Self::CallMethodDescriptorFast => 2 + oparg,
            Self::CallMethodDescriptorFastWithKeywords => 2 + oparg,
            Self::CallMethodDescriptorNoargs => 2 + oparg,
            Self::CallMethodDescriptorO => 2 + oparg,
            Self::CallNonPyGeneral => 2 + oparg,
            Self::CallPyExactArgs => 2 + oparg,
            Self::CallPyGeneral => 2 + oparg,
            Self::CallStr1 => 3,
            Self::CallTuple1 => 3,
            Self::CallType1 => 3,
            Self::CheckEgMatch => 2,
            Self::CheckExcMatch => 2,
            Self::CleanupThrow => 3,
            Self::CompareOp => 2,
            Self::CompareOpFloat => 2,
            Self::CompareOpInt => 2,
            Self::CompareOpStr => 2,
            Self::ContainsOp => 2,
            Self::ContainsOpDict => 2,
            Self::ContainsOpSet => 2,
            Self::ConvertValue => 1,
            Self::Copy => 1 + (oparg - 1),
            Self::CopyFreeVars => 0,
            Self::DeleteAttr => 1,
            Self::DeleteDeref => 0,
            Self::DeleteFast => 0,
            Self::DeleteGlobal => 0,
            Self::DeleteName => 0,
            Self::DeleteSubscr => 2,
            Self::DictMerge => 5 + (oparg - 1),
            Self::DictUpdate => 2 + (oparg - 1),
            Self::EndAsyncFor => 2,
            Self::EndFor => 1,
            Self::EndSend => 2,
            Self::EnterExecutor => 0,
            Self::ExitInitCheck => 1,
            Self::ExtendedArg => 0,
            Self::FormatSimple => 1,
            Self::FormatWithSpec => 2,
            Self::ForIter => 1,
            Self::ForIterGen => 1,
            Self::ForIterList => 1,
            Self::ForIterRange => 1,
            Self::ForIterTuple => 1,
            Self::GetAiter => 1,
            Self::GetAnext => 1,
            Self::GetAwaitable => 1,
            Self::GetIter => 1,
            Self::GetLen => 1,
            Self::GetYieldFromIter => 1,
            Self::ImportFrom => 1,
            Self::ImportName => 2,
            Self::InstrumentedCall => 0,
            Self::InstrumentedCallFunctionEx => 0,
            Self::InstrumentedCallKw => 0,
            Self::InstrumentedEndFor => 2,
            Self::InstrumentedEndSend => 2,
            Self::InstrumentedForIter => 0,
            Self::InstrumentedInstruction => 0,
            Self::InstrumentedJumpBackward => 0,
            Self::InstrumentedJumpForward => 0,
            Self::InstrumentedLoadSuperAttr => 3,
            Self::InstrumentedPopJumpIfFalse => 0,
            Self::InstrumentedPopJumpIfNone => 0,
            Self::InstrumentedPopJumpIfNotNone => 0,
            Self::InstrumentedPopJumpIfTrue => 0,
            Self::InstrumentedResume => 0,
            Self::InstrumentedReturnConst => 0,
            Self::InstrumentedReturnValue => 1,
            Self::InstrumentedYieldValue => 1,
            Self::InterpreterExit => 1,
            Self::IsOp => 2,
            Self::JumpBackward => 0,
            Self::JumpBackwardNoInterrupt => 0,
            Self::JumpForward => 0,
            Self::ListAppend => 2 + (oparg - 1),
            Self::ListExtend => 2 + (oparg - 1),
            Self::LoadAssertionError => 0,
            Self::LoadAttr => 1,
            Self::LoadAttrClass => 1,
            Self::LoadAttrGetattributeOverridden => 1,
            Self::LoadAttrInstanceValue => 1,
            Self::LoadAttrMethodLazyDict => 1,
            Self::LoadAttrMethodNoDict => 1,
            Self::LoadAttrMethodWithValues => 1,
            Self::LoadAttrModule => 1,
            Self::LoadAttrNondescriptorNoDict => 1,
            Self::LoadAttrNondescriptorWithValues => 1,
            Self::LoadAttrProperty => 1,
            Self::LoadAttrSlot => 1,
            Self::LoadAttrWithHint => 1,
            Self::LoadBuildClass => 0,
            Self::LoadConst => 0,
            Self::LoadDeref => 0,
            Self::LoadFast => 0,
            Self::LoadFastAndClear => 0,
            Self::LoadFastCheck => 0,
            Self::LoadFastLoadFast => 0,
            Self::LoadFromDictOrDeref => 1,
            Self::LoadFromDictOrGlobals => 1,
            Self::LoadGlobal => 0,
            Self::LoadGlobalBuiltin => 0,
            Self::LoadGlobalModule => 0,
            Self::LoadLocals => 0,
            Self::LoadName => 0,
            Self::LoadSuperAttr => 3,
            Self::LoadSuperAttrAttr => 3,
            Self::LoadSuperAttrMethod => 3,
            Self::MakeCell => 0,
            Self::MakeFunction => 1,
            Self::MapAdd => 3 + (oparg - 1),
            Self::MatchClass => 3,
            Self::MatchKeys => 2,
            Self::MatchMapping => 1,
            Self::MatchSequence => 1,
            Self::Nop => 0,
            Self::PopExcept => 1,
            Self::PopJumpIfFalse => 1,
            Self::PopJumpIfNone => 1,
            Self::PopJumpIfNotNone => 1,
            Self::PopJumpIfTrue => 1,
            Self::PopTop => 1,
            Self::PushExcInfo => 1,
            Self::PushNull => 0,
            Self::RaiseVarargs => oparg,
            Self::Reraise => 1 + oparg,
            Self::Reserved => 0,
            Self::Resume => 0,
            Self::ResumeCheck => 0,
            Self::ReturnConst => 0,
            Self::ReturnGenerator => 0,
            Self::ReturnValue => 1,
            Self::Send => 2,
            Self::SendGen => 2,
            Self::SetupAnnotations => 0,
            Self::SetAdd => 2 + (oparg - 1),
            Self::SetFunctionAttribute => 2,
            Self::SetUpdate => 2 + (oparg - 1),
            Self::StoreAttr => 2,
            Self::StoreAttrInstanceValue => 2,
            Self::StoreAttrSlot => 2,
            Self::StoreAttrWithHint => 2,
            Self::StoreDeref => 1,
            Self::StoreFast => 1,
            Self::StoreFastLoadFast => 1,
            Self::StoreFastStoreFast => 2,
            Self::StoreGlobal => 1,
            Self::StoreName => 1,
            Self::StoreSlice => 4,
            Self::StoreSubscr => 3,
            Self::StoreSubscrDict => 3,
            Self::StoreSubscrListInt => 3,
            Self::Swap => 2 + (oparg - 2),
            Self::ToBool => 1,
            Self::ToBoolAlwaysTrue => 1,
            Self::ToBoolBool => 1,
            Self::ToBoolInt => 1,
            Self::ToBoolList => 1,
            Self::ToBoolNone => 1,
            Self::ToBoolStr => 1,
            Self::UnaryInvert => 1,
            Self::UnaryNegative => 1,
            Self::UnaryNot => 1,
            Self::UnpackEx => 1,
            Self::UnpackSequence => 1,
            Self::UnpackSequenceList => 1,
            Self::UnpackSequenceTuple => 1,
            Self::UnpackSequenceTwoTuple => 1,
            Self::WithExceptStart => 4,
            Self::YieldValue => 1,
            _ => panic!("Pseudo opcodes are not allowed!"),
        }
    }

    /// How many items should be pushed on the stack.
    pub const fn num_pushed(&self, oparg: u32) -> u32 {
        match &self {
            Self::BeforeAsyncWith => 2,
            Self::BeforeWith => 2,
            Self::BinaryOp => 1,
            Self::BinaryOpAddFloat => 1,
            Self::BinaryOpAddInt => 1,
            Self::BinaryOpAddUnicode => 1,
            Self::BinaryOpInplaceAddUnicode => 0,
            Self::BinaryOpMultiplyFloat => 1,
            Self::BinaryOpMultiplyInt => 1,
            Self::BinaryOpSubtractFloat => 1,
            Self::BinaryOpSubtractInt => 1,
            Self::BinarySlice => 1,
            Self::BinarySubscr => 1,
            Self::BinarySubscrDict => 1,
            Self::BinarySubscrGetitem => 1,
            Self::BinarySubscrListInt => 1,
            Self::BinarySubscrStrInt => 1,
            Self::BinarySubscrTupleInt => 1,
            Self::BuildConstKeyMap => 1,
            Self::BuildList => 1,
            Self::BuildMap => 1,
            Self::BuildSet => 1,
            Self::BuildSlice => 1,
            Self::BuildString => 1,
            Self::BuildTuple => 1,
            Self::Cache => 0,
            Self::Call => 1,
            Self::CallAllocAndEnterInit => 1,
            Self::CallBoundMethodExactArgs => 0,
            Self::CallBoundMethodGeneral => 0,
            Self::CallBuiltinClass => 1,
            Self::CallBuiltinFast => 1,
            Self::CallBuiltinFastWithKeywords => 1,
            Self::CallBuiltinO => 1,
            Self::CallFunctionEx => 1,
            Self::CallIntrinsic1 => 1,
            Self::CallIntrinsic2 => 1,
            Self::CallIsinstance => 1,
            Self::CallKw => 1,
            Self::CallLen => 1,
            Self::CallListAppend => 1,
            Self::CallMethodDescriptorFast => 1,
            Self::CallMethodDescriptorFastWithKeywords => 1,
            Self::CallMethodDescriptorNoargs => 1,
            Self::CallMethodDescriptorO => 1,
            Self::CallNonPyGeneral => 1,
            Self::CallPyExactArgs => 0,
            Self::CallPyGeneral => 0,
            Self::CallStr1 => 1,
            Self::CallTuple1 => 1,
            Self::CallType1 => 1,
            Self::CheckEgMatch => 2,
            Self::CheckExcMatch => 2,
            Self::CleanupThrow => 2,
            Self::CompareOp => 1,
            Self::CompareOpFloat => 1,
            Self::CompareOpInt => 1,
            Self::CompareOpStr => 1,
            Self::ContainsOp => 1,
            Self::ContainsOpDict => 1,
            Self::ContainsOpSet => 1,
            Self::ConvertValue => 1,
            Self::Copy => 2 + (oparg - 1),
            Self::CopyFreeVars => 0,
            Self::DeleteAttr => 0,
            Self::DeleteDeref => 0,
            Self::DeleteFast => 0,
            Self::DeleteGlobal => 0,
            Self::DeleteName => 0,
            Self::DeleteSubscr => 0,
            Self::DictMerge => 4 + (oparg - 1),
            Self::DictUpdate => 1 + (oparg - 1),
            Self::EndAsyncFor => 0,
            Self::EndFor => 0,
            Self::EndSend => 1,
            Self::EnterExecutor => 0,
            Self::ExitInitCheck => 0,
            Self::ExtendedArg => 0,
            Self::FormatSimple => 1,
            Self::FormatWithSpec => 1,
            Self::ForIter => 2,
            Self::ForIterGen => 1,
            Self::ForIterList => 2,
            Self::ForIterRange => 2,
            Self::ForIterTuple => 2,
            Self::GetAiter => 1,
            Self::GetAnext => 2,
            Self::GetAwaitable => 1,
            Self::GetIter => 1,
            Self::GetLen => 2,
            Self::GetYieldFromIter => 1,
            Self::ImportFrom => 2,
            Self::ImportName => 1,
            Self::InstrumentedCall => 0,
            Self::InstrumentedCallFunctionEx => 0,
            Self::InstrumentedCallKw => 0,
            Self::InstrumentedEndFor => 1,
            Self::InstrumentedEndSend => 1,
            Self::InstrumentedForIter => 0,
            Self::InstrumentedInstruction => 0,
            Self::InstrumentedJumpBackward => 0,
            Self::InstrumentedJumpForward => 0,
            Self::InstrumentedLoadSuperAttr => 1 + (oparg & 1),
            Self::InstrumentedPopJumpIfFalse => 0,
            Self::InstrumentedPopJumpIfNone => 0,
            Self::InstrumentedPopJumpIfNotNone => 0,
            Self::InstrumentedPopJumpIfTrue => 0,
            Self::InstrumentedResume => 0,
            Self::InstrumentedReturnConst => 0,
            Self::InstrumentedReturnValue => 0,
            Self::InstrumentedYieldValue => 1,
            Self::InterpreterExit => 0,
            Self::IsOp => 1,
            Self::JumpBackward => 0,
            Self::JumpBackwardNoInterrupt => 0,
            Self::JumpForward => 0,
            Self::ListAppend => 1 + (oparg - 1),
            Self::ListExtend => 1 + (oparg - 1),
            Self::LoadAssertionError => 1,
            Self::LoadAttr => 1 + (oparg & 1),
            Self::LoadAttrClass => 1 + (oparg & 1),
            Self::LoadAttrGetattributeOverridden => 1,
            Self::LoadAttrInstanceValue => 1 + (oparg & 1),
            Self::LoadAttrMethodLazyDict => 2,
            Self::LoadAttrMethodNoDict => 2,
            Self::LoadAttrMethodWithValues => 2,
            Self::LoadAttrModule => 1 + (oparg & 1),
            Self::LoadAttrNondescriptorNoDict => 1,
            Self::LoadAttrNondescriptorWithValues => 1,
            Self::LoadAttrProperty => 1,
            Self::LoadAttrSlot => 1 + (oparg & 1),
            Self::LoadAttrWithHint => 1 + (oparg & 1),
            Self::LoadBuildClass => 1,
            Self::LoadConst => 1,
            Self::LoadDeref => 1,
            Self::LoadFast => 1,
            Self::LoadFastAndClear => 1,
            Self::LoadFastCheck => 1,
            Self::LoadFastLoadFast => 2,
            Self::LoadFromDictOrDeref => 1,
            Self::LoadFromDictOrGlobals => 1,
            Self::LoadGlobal => 1 + (oparg & 1),
            Self::LoadGlobalBuiltin => 1 + (oparg & 1),
            Self::LoadGlobalModule => 1 + (oparg & 1),
            Self::LoadLocals => 1,
            Self::LoadName => 1,
            Self::LoadSuperAttr => 1 + (oparg & 1),
            Self::LoadSuperAttrAttr => 1,
            Self::LoadSuperAttrMethod => 2,
            Self::MakeCell => 0,
            Self::MakeFunction => 1,
            Self::MapAdd => 1 + (oparg - 1),
            Self::MatchClass => 1,
            Self::MatchKeys => 3,
            Self::MatchMapping => 2,
            Self::MatchSequence => 2,
            Self::Nop => 0,
            Self::PopExcept => 0,
            Self::PopJumpIfFalse => 0,
            Self::PopJumpIfNone => 0,
            Self::PopJumpIfNotNone => 0,
            Self::PopJumpIfTrue => 0,
            Self::PopTop => 0,
            Self::PushExcInfo => 2,
            Self::PushNull => 1,
            Self::RaiseVarargs => 0,
            Self::Reraise => oparg,
            Self::Reserved => 0,
            Self::Resume => 0,
            Self::ResumeCheck => 0,
            Self::ReturnConst => 0,
            Self::ReturnGenerator => 1,
            Self::ReturnValue => 0,
            Self::Send => 2,
            Self::SendGen => 2,
            Self::SetupAnnotations => 0,
            Self::SetAdd => 1 + (oparg - 1),
            Self::SetFunctionAttribute => 1,
            Self::SetUpdate => 1 + (oparg - 1),
            Self::StoreAttr => 0,
            Self::StoreAttrInstanceValue => 0,
            Self::StoreAttrSlot => 0,
            Self::StoreAttrWithHint => 0,
            Self::StoreDeref => 0,
            Self::StoreFast => 0,
            Self::StoreFastLoadFast => 1,
            Self::StoreFastStoreFast => 0,
            Self::StoreGlobal => 0,
            Self::StoreName => 0,
            Self::StoreSlice => 0,
            Self::StoreSubscr => 0,
            Self::StoreSubscrDict => 0,
            Self::StoreSubscrListInt => 0,
            Self::Swap => 2 + (oparg - 2),
            Self::ToBool => 1,
            Self::ToBoolAlwaysTrue => 1,
            Self::ToBoolBool => 1,
            Self::ToBoolInt => 1,
            Self::ToBoolList => 1,
            Self::ToBoolNone => 1,
            Self::ToBoolStr => 1,
            Self::UnaryInvert => 1,
            Self::UnaryNegative => 1,
            Self::UnaryNot => 1,
            Self::UnpackEx => 1 + (oparg >> 8) + (oparg & 0xFF),
            Self::UnpackSequence => oparg,
            Self::UnpackSequenceList => oparg,
            Self::UnpackSequenceTuple => oparg,
            Self::UnpackSequenceTwoTuple => 2,
            Self::WithExceptStart => 5,
            Self::YieldValue => 1,
            _ => panic!("Pseudo opcodes are not allowed!"),
        }
    }
}

macro_rules! opcode_try_from_impl {
    ($t:ty) => {
        impl TryFrom<$t> for Opcode {
            type Error = ();

            fn try_from(value: $t) -> Result<Self, Self::Error> {
                let id = value.try_into().map_err(|_| ())?;
                if Self::is_valid(id) {
                    // SAFETY: We just validated that we have a valid opcode id.
                    Ok(unsafe { std::mem::transmute::<u16, Self>(id) })
                } else {
                    Err(())
                }
            }
        }
    };
}

opcode_try_from_impl!(i8);
opcode_try_from_impl!(i16);
opcode_try_from_impl!(i32);
opcode_try_from_impl!(i64);
opcode_try_from_impl!(i128);
opcode_try_from_impl!(isize);
opcode_try_from_impl!(u8);
opcode_try_from_impl!(u16);
opcode_try_from_impl!(u32);
opcode_try_from_impl!(u64);
opcode_try_from_impl!(u128);
opcode_try_from_impl!(usize);
