[project]
name = "rpau"
version = "0.1.0"
description = "Tool for automaticly update Lib & Tests from CPython"
readme = "README.md"
authors = [
    { name = "RustPython Team", email = "" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
rpau = "rpau:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
