[Opcode]
instruction_enum = "Instruction"
numeric_repr = "u8"
range = { min = 0, max = 255 }

[Opcode.opcodes.ContainsOp]
oparg = { name = "invert", type = "oparg::Invert" }

[PseudoOpcode]
instruction_enum = "PseudoInstruction"
numeric_repr = "u16"
range = { min = 256, max = 65535 }

