//! This package contains the python basic/builtin types

pub mod asyncgenerator;
pub mod builtinfunc;
pub mod bytearray;
pub mod bytes;
pub mod classmethod;
pub mod code;
pub mod complex;
pub mod coroutine;
pub mod dict;
pub mod enumerate;
pub mod filter;
pub mod float;
pub mod frame;
pub mod function;
pub mod generator;
pub mod getset;
pub mod int;
pub mod iter;
pub mod list;
pub mod map;
pub mod mappingproxy;
pub mod memory;
pub mod module;
pub mod namespace;
pub mod object;
pub mod property;
pub mod pybool;
pub mod pystr;
pub mod pysuper;
pub mod pytype;
pub mod range;
pub mod set;
pub mod singletons;
pub mod slice;
pub mod staticmethod;
pub mod traceback;
pub mod tuple;
pub mod weakproxy;
pub mod weakref;
pub mod zip;

mod make_module;
pub use make_module::*;
