[package]
name = "rustpython-ast"
version = "0.2.0"
description = "AST definitions for RustPython"
authors = ["RustPython Team"]
edition = "2021"
repository = "https://github.com/RustPython/RustPython"
license = "MIT"

[features]
default = ["constant-optimization", "fold"]
constant-optimization = ["fold"]
fold = []
unparse = ["rustpython-common"]

[dependencies]
rustpython-compiler-core = { path = "../core", version = "0.2.0" }
rustpython-common = { path = "../../common", version = "0.2.0", optional = true }

num-bigint = { workspace = true }
